version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"   # Expone el puerto 8080 para acceder a la aplicación
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: snippet-share
    ports:
      - "3308:3306"
